#!/bin/bash
# This hook is run before every virtualenv is activated.

# must launch sublime BEFORE activating the venv to avoid installing Sublime Text 2 Packages in the venv, etc

export PROJECT_HOME_BEFORE_VENV=$PROJECT_HOME
export PWD_BEFORE_VENV=$(pwd)
export PROJECT_NAME_AFTER_VENV=$1




# don't use $WORKON_HOME in case this script is in a particular VENV
# TODO: use path of the current bash script
if [ -f $(which find_project_dir.py) ]; then
    PRJDIR=$(find_project_dir.py "$PROJECT_NAME_AFTER_VENV")
    # echo "PRJDIR = $PRJDIR" 1>&2;
    PRJNAME=$(basename $PRJDIR)
    # echo "PRJNAME = $PRJNAME" 1>&2;
    cd "$PRJDIR"
    # TODO, look for ~/src/sublime-projects/PRJ_NAME.sublime-project and load it rather than the entire PRJ dir
    if [ -f $(which sublime) ]; then
        if [ -f "${HOME}/src/.sublime-projects/${PRJNAME}.sublime-project" ]; then
            sublime --project "${HOME}/src/.sublime-projects/${PRJNAME}.sublime-project" &
        else
            sublime "$PRJDIR/"
            #echo "Unable to find a project directory so didn't launch Sublime Text 2 text editor." 1>&2;
        fi
    fi
fi